kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx_pod_3
  template:
    metadata:
      labels:
        app: nginx_pod_3
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.6-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
