kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-deployment-2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx_pod_2
    spec:
      containers:
      - image: nginx:1.17.6-alpine
        imagePullPolicy: IfNotPresent
        name: "2048"
        ports:
        - containerPort: 80
